openapi: 3.0.3
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: >
        JSON Web Token (JWT) authentication using the Bearer scheme. 
        Enter your JWT token in the format `Bearer <token>`.

security:
  - bearerAuth: []
