version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: farmers_marketplace_api
    ports:
      - '8000:8000'
    environment:
      - ENVIRONMENT=development
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
      - DATABASE_URL=postgresql+asyncpg://myuser:mypassword@postgres:5432/mydatabase
    volumes:
      - .:/app
      - /app/__pycache__
    depends_on:
      - postgres
    networks:
      - farmers_marketplace_network

  postgres:
    image: postgres:13
    container_name: farmers_marketplace_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - farmers_marketplace_network

volumes:
  postgres_data:

networks:
  farmers_marketplace_network:
    driver: bridge
