version: '3.8'

services:
  app:
    build:
      context: ../..
      dockerfile: Dockerfile
    image: revo-backend:latest
    container_name: revo-backend
    restart: unless-stopped
    env_file:
      - ./env/${NODE_ENV:-dev}/.env
    ports:
      - "3000:3000"
    volumes:
      - ./security:/app/config/security
      - ./secrets:/run/secrets:ro
    secrets:
      - db_password
      - jwt_secret
      - ssl_key
      - ssl_cert
      - vault_token
    security_opt:
      - no-new-privileges:true
      - no-sandbox:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/run
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    depends_on:
      - postgres
      - vault

  postgres:
    image: postgres:15-alpine
    container_name: revo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./secrets:/run/secrets:ro
    secrets:
      - db_password
    security_opt:
      - no-new-privileges:true
      - no-sandbox:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/run

  vault:
    image: hashicorp/vault:1.13
    container_name: revo-vault
    restart: unless-stopped
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_TOKEN}
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "8200:8200"
    volumes:
      - vault_data:/vault/data
      - ./security:/vault/config
    cap_add:
      - IPC_LOCK
    security_opt:
      - no-new-privileges:true
      - no-sandbox:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/run

  vault-agent:
    image: hashicorp/vault:1.13
    container_name: revo-vault-agent
    restart: unless-stopped
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: ${VAULT_TOKEN}
    volumes:
      - ./security:/vault/config
      - ./secrets:/vault/secrets
    depends_on:
      - vault
    security_opt:
      - no-new-privileges:true
      - no-sandbox:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/run

volumes:
  postgres_data:
  vault_data:

secrets:
  db_password:
    file: ./secrets/db_password.txt
  jwt_secret:
    file: ./secrets/jwt_secret.txt
  ssl_key:
    file: ./secrets/ssl_key.pem
  ssl_cert:
    file: ./secrets/ssl_cert.pem
  vault_token:
    file: ./secrets/vault_token.txt 