version: '1.0'

security:
  # Password Policy
  password_policy:
    min_length: 12
    require_uppercase: true
    require_lowercase: true
    require_numbers: true
    require_special_chars: true
    max_age_days: 90
    history_size: 5

  # JWT Configuration
  jwt:
    algorithm: 'RS256'
    key_rotation_days: 30
    blacklist_enabled: true
    blacklist_ttl: 24h

  # Rate Limiting
  rate_limiting:
    enabled: true
    window_ms: 60000
    max_requests: 100
    skip_failed_requests: false

  # CORS Configuration
  cors:
    allowed_origins: ['${CORS_ORIGIN}']
    allowed_methods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH']
    allowed_headers: ['Content-Type', 'Authorization']
    exposed_headers: ['Content-Range', 'X-Content-Range']
    credentials: true
    max_age: 86400

  # SSL/TLS Configuration
  ssl:
    min_version: 'TLSv1.2'
    ciphers:
      [
        'ECDHE-ECDSA-AES128-GCM-SHA256',
        'ECDHE-RSA-AES128-GCM-SHA256',
        'ECDHE-ECDSA-AES256-GCM-SHA384',
        'ECDHE-RSA-AES256-GCM-SHA384',
      ]
    certificate_rotation_days: 90

  # Audit Configuration
  audit:
    enabled: true
    log_level: 'info'
    sensitive_fields: ['password', 'token', 'secret']
    retention_days: 90

  # Vault Configuration
  vault:
    enabled: true
    secret_rotation:
      enabled: true
      interval_days: 30
      grace_period_days: 7
    paths:
      database: 'secret/database'
      jwt: 'secret/jwt'
      api_keys: 'secret/api_keys'

  # Docker Security
  docker:
    read_only_root_filesystem: true
    no_new_privileges: true
    capabilities:
      drop: ['ALL']
    security_opt:
      - 'no-new-privileges:true'
      - 'no-sandbox:true'
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
